# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release branch workflow

on:
  pull_request:
    branches: [ "release" ]

jobs:

  testing:
    uses: ./.github/workflows/workflow-tests.yml

  tagging:
    if: ${{ always() }}
    needs: [testing]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: butlerlogic/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  netlify-release:
    if: ${{ always() }}
    needs: [tagging]

    uses: ./.github/workflows/workflow-netfliy.yml

  npm-release:
    if: ${{ always() }}
    needs: [tagging]

    uses: ./.github/workflows/workflow-npm.yml