name: Release branch workflow

on:
  pull_request:
    branches: ['release']

jobs:
  testing:
    uses: ./.github/workflows/workflow-tests.yml

  tagging:
    if: ${{ always() }}
    needs: [testing]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
