name: Create storybook demo and deploy on netlify

on:
  workflow_call:

jobs:
  storybook-build-and-deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Build storybook
      run: npm ci;  run build-storybook
    
    - name: Deploy to netlify
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
        args: deploy --dir=storybook-static --prod
        secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'