# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Automated linter and testing 

on:
  workflow_call:

jobs:

  lint-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
     - uses: actions/checkout@v3
     
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v3
       with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
     
     - name: Cache dependencies
       id: cache
       uses: actions/cache@v2
       with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

     - name: Install dependencies
       if: steps.cache.outputs.cache-hit != 'true'
       run: npm ci --ignore-scripts

     - name: Build project
       run: npm run build --if-present

     - name: Run prettier
       run: npm run lint
     
     - name: Run tests
       run: npm run test