# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build package and deploy on npm

on:
  workflow_call:


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - run: |
        npm run package
        npm publish ./package
    